services:
  mysql:
    build:
      context: ./backend/mysql  # Path to your custom MySQL Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: task  # This is where the task database will be created
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    networks:
      - app-network
    ports:
      - "3306:3306"

  php-fpm:
    build:
      context: ./backend/php-fpm
    container_name: php-fpm
    volumes:
      - ./backend/src:/var/www/html
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: examplepassword
      JWT_SIGN_KEY: "what-does-the-fox-say?"
      IS_DEV: 'true'  # Or 'false' based on your environment
    depends_on:
      - mysql

  nginx:
    build:
      context: ./backend/nginx
    container_name: nginx
    ports:
      - "4000:80"
    depends_on:
      - php-fpm
    networks:
      - app-network
  
  front-end-nginx:
    image: nginx:latest
    container_name: front-end-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build/:/usr/share/nginx/html/

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: