services:
  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
